package project_classes;


public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        personelGirisiButton = new javax.swing.JButton();
        musteriGirisiButton = new javax.swing.JButton();
        adminGirisiButton = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOTEL");

        personelGirisiButton.setForeground(new java.awt.Color(51, 204, 255));
        personelGirisiButton.setText("Personel Girişi");
        personelGirisiButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        personelGirisiButton.setFocusable(false);
        personelGirisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelGirisiButtonActionPerformed(evt);
            }
        });

        musteriGirisiButton.setForeground(new java.awt.Color(255, 153, 0));
        musteriGirisiButton.setText("Müşteri Girişi");
        musteriGirisiButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        musteriGirisiButton.setFocusable(false);
        musteriGirisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriGirisiButtonActionPerformed(evt);
            }
        });

        adminGirisiButton.setForeground(new java.awt.Color(153, 0, 255));
        adminGirisiButton.setText("Admin Girişi");
        adminGirisiButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminGirisiButton.setFocusable(false);
        adminGirisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminGirisiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminGirisiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(musteriGirisiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(personelGirisiButton))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adminGirisiButton, musteriGirisiButton, personelGirisiButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(personelGirisiButton)
                .addGap(77, 77, 77)
                .addComponent(musteriGirisiButton)
                .addGap(72, 72, 72)
                .addComponent(adminGirisiButton)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void personelGirisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelGirisiButtonActionPerformed
        EmployeeLogin employeelogin = new EmployeeLogin();
        employeelogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_personelGirisiButtonActionPerformed

    private void adminGirisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminGirisiButtonActionPerformed
       AdminLogin adminlogin = new AdminLogin();
       adminlogin.setVisible(true);
       dispose();
    }//GEN-LAST:event_adminGirisiButtonActionPerformed

    private void musteriGirisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriGirisiButtonActionPerformed
        CustomerLogin cst = new CustomerLogin();
        cst.setVisible(true);
        dispose();
    }//GEN-LAST:event_musteriGirisiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminGirisiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton musteriGirisiButton;
    private javax.swing.JButton personelGirisiButton;
    // End of variables declaration//GEN-END:variables
}
